provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  echo:
    lang: go
    handler: ./echo
    image: ewilde/echo:latest
    environment:
      combine_output: "false"
  cert-sign-go:
    lang: go
    handler: ./cert-sign-go
    image: ewilde/cert-sign-go:latest
  faas-lambda-jwt-page:
    lang: node8-express
    handler: ./faas-lambda-jwt-page
    image: ewilde/faas-lambda-jwt-page:latest
  faas-lambda-jwt-oauth2-callback:
    lang: golang-middleware
    handler: ./faas-lambda-jwt-oauth2-callback
    image: ewilde/faas-lambda-jwt-oauth2-callback:latest
    secrets:
      - faas-lambda
    environment:
      combine_output: "false"