provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  echo:
    lang: go
    handler: ./echo
    image: ewilde/echo:latest
    environment:
      combine_output: "false"
  cert-sign-go:
    lang: go
    handler: ./cert-sign-go
    image: ewilde/cert-sign-go:latest